### ISSUE TITLE
Possible additions

### ISSUE THREAD

**Issue by richfitz** [rseng/awesome-rseng#8]
Not sure what categories these might fit in, but 3 organisations from our RSE work within the [MRC centre for global infectious disease analysis](https://www.imperial.ac.uk/mrc-global-infectious-disease-analysis)

* https://github.com/mrc-ide/ - this is our departmental github org and includes open source work from both the engineering end of the department through to very much the scientific end (>100 public repositories)
* https://github.com/vimc/ - a separate organisation that we use to support a [major initative](https://vaccineimpact.org/) within the department (60 public repositories, many of which are standalone or reusable components)
* https://github.com/reside-ic/ - the org for the [RSE team itself](https://reside-ic.github.io/about/)

I'm not sure how one might spread these out of the categories that you have currently - academic groups or a section on medicine/epidemiology?

**Comment by vsoch** [comment]
hey @richfitz - what about Health Informatics, or more generally, Health and Medicine? Under Health and Medicine, we could definitely do a section for Epidemiology - that seems like a good fit!  If you consider the third more of a kind of lab, it could fit under academic lab too - it's really up to how you self identify.

Do you have specific repos under these three that have one or more "good first issues?" I'm building a web interface that will grab them nightly and update a GitHub pages so a visitor can find interesting projects to help with.

**Comment by richfitz** [comment]
Health and Medicine sounds good.  For the latter one we're not a lab - perhaps a group?  Similar to the Imperial College London group perhaps, with whom we are friendly (and through whom I found this list!)

Unfortunately practically all our issue tracking is on a private youtrack, and we barely use the github tracker

**Comment by vsoch** [comment]
Ah okay, that's no issue! If there ever are repos that pop up as good places to direct new contributors, we can add later.

Would you like to open a PR, or if you don't have the bandwidth, I can add to my queue to do?

**Comment by vsoch** [comment]
@richfitz how does this look? https://github.com/rseng/awesome-rseng#epidemiology

**Comment by richfitz** [comment]
Thank you - that looks great 😄

**Comment by vsoch** [comment]
Great! Closing issue.
